export type Muscle =
  | "CHEST"
  | "BACK"
  | "SHOULDERS"
  | "LEGS"
  | "ARMS"
  | "CORE";

export type Category =
  | "POWERLIFTING"
  | "OLYMPIC"
  | "STRONGMAN"
  | "CROSSFIT"
  | "CALISTHENICS"
  | "PLYOMETRIC"
  | "STRETCH";

export type Exercise = {
  id: string;
  name: string;
  muscle: Muscle;
  categories: Category[];
  description: string;
};

export const MUSCLES: Muscle[] = [
  "CHEST",
  "BACK",
  "SHOULDERS",
  "LEGS",
  "ARMS",
  "CORE",
];

export const CATEGORIES: Category[] = [
  "POWERLIFTING",
  "OLYMPIC",
  "STRONGMAN",
  "CROSSFIT",
  "CALISTHENICS",
  "PLYOMETRIC",
  "STRETCH",
];

export const exercises: Exercise[] = [
  // CHEST
  {
    id: "ch1",
    name: "Barbell Bench Press",
    muscle: "CHEST",
    categories: ["POWERLIFTING"],
    description:
      "The primary flat-bench press. Retract your shoulder blades and drive the bar over mid-chest for max pec and triceps power.",
  },
  {
    id: "ch2",
    name: "Incline Barbell Bench Press",
    muscle: "CHEST",
    categories: ["POWERLIFTING"],
    description: "Bench set to 30-45 degrees to emphasize the upper chest and front delts.",
  },
  {
    id: "ch3",
    name: "Decline Barbell Bench Press",
    muscle: "CHEST",
    categories: ["POWERLIFTING"],
    description: "Bench angled downward to bias the lower-chest fibers.",
  },
  {
    id: "ch4",
    name: "Dumbbell Bench Press",
    muscle: "CHEST",
    categories: [],
    description: "Flat dumbbell press for deeper stretch and independent arm tracking.",
  },
  {
    id: "ch5",
    name: "Incline Dumbbell Press",
    muscle: "CHEST",
    categories: [],
    description: "Upper-chest emphasis with a deeper dumbbell stretch.",
  },
  {
    id: "ch6",
    name: "Cable Fly",
    muscle: "CHEST",
    categories: [],
    description: "Constant-tension pec isolation across a fly arc.",
  },
  {
    id: "ch7",
    name: "Dips (Chest)",
    muscle: "CHEST",
    categories: ["CALISTHENICS"],
    description: "Lean forward to bias the pecs; upright torso hits triceps.",
  },
  {
    id: "ch8",
    name: "Push-Up",
    muscle: "CHEST",
    categories: ["CALISTHENICS", "PLYOMETRIC"],
    description: "Bodyweight chest staple. Stack shoulders over wrists, elbows ~45°.",
  },
  {
    id: "ch9",
    name: "Machine Chest Press",
    muscle: "CHEST",
    categories: [],
    description: "Stack-loaded horizontal press for controlled pec loading.",
  },

  // BACK
  {
    id: "bk1",
    name: "Deadlift",
    muscle: "BACK",
    categories: ["POWERLIFTING", "STRONGMAN"],
    description:
      "Hinge off the floor. Brace, pull the slack out, drive the floor away. The test of full-body strength.",
  },
  {
    id: "bk1b",
    name: "Sumo Deadlift",
    muscle: "BACK",
    categories: ["POWERLIFTING"],
    description:
      "Wide-stance deadlift with the hands inside the knees. More leg drive, less lower-back demand — great for long-limbed lifters.",
  },
  {
    id: "bk1c",
    name: "Conventional Deadlift",
    muscle: "BACK",
    categories: ["POWERLIFTING"],
    description:
      "Shoulder-width stance, hands outside the knees. Max posterior-chain and back demand.",
  },
  {
    id: "bk1d",
    name: "Deficit Deadlift",
    muscle: "BACK",
    categories: ["POWERLIFTING", "STRONGMAN"],
    description:
      "Stand on a plate and pull from below standard height — builds speed off the floor and range.",
  },
  {
    id: "bk1e",
    name: "Block Pull / Rack Pull",
    muscle: "BACK",
    categories: ["POWERLIFTING", "STRONGMAN"],
    description:
      "Pull from elevated blocks or pins — overloads the lockout and upper back.",
  },
  {
    id: "bk1f",
    name: "Snatch-Grip Deadlift",
    muscle: "BACK",
    categories: ["OLYMPIC"],
    description:
      "Wide-grip deadlift for extra range and upper-back work; transfers to the snatch pull.",
  },
  {
    id: "bk2",
    name: "Pull-Up",
    muscle: "BACK",
    categories: ["CALISTHENICS"],
    description: "Vertical pulling staple for lats. Pull elbows down and back.",
  },
  {
    id: "bk3",
    name: "Barbell Row",
    muscle: "BACK",
    categories: [],
    description: "Bent-over row for mid-back density. Hinge to ~45° and row to the belt line.",
  },
  {
    id: "bk4",
    name: "Pendlay Row",
    muscle: "BACK",
    categories: ["POWERLIFTING"],
    description: "Dead-stop barbell row from the floor each rep — explosive pull.",
  },
  {
    id: "bk5",
    name: "Lat Pulldown",
    muscle: "BACK",
    categories: [],
    description: "Cable vertical pull; substitute for pull-ups to build volume.",
  },
  {
    id: "bk6",
    name: "Seated Cable Row",
    muscle: "BACK",
    categories: [],
    description: "Horizontal cable pull with a controlled stretch.",
  },
  {
    id: "bk7",
    name: "Dumbbell Row",
    muscle: "BACK",
    categories: [],
    description: "Single-arm row for symmetrical back development.",
  },
  {
    id: "bk8",
    name: "Face Pull",
    muscle: "BACK",
    categories: ["STRETCH"],
    description: "Rear-delt and upper-back health. Pull rope to forehead, elbows high.",
  },
  {
    id: "bk9",
    name: "Barbell Shrug",
    muscle: "BACK",
    categories: [],
    description: "Trap isolation. Shrug straight up, no rotation.",
  },
  {
    id: "bk10",
    name: "Rack Pull",
    muscle: "BACK",
    categories: ["STRONGMAN", "POWERLIFTING"],
    description: "Partial deadlift from the racks — overload the lockout and upper back.",
  },

  // SHOULDERS
  {
    id: "sh1",
    name: "Overhead Press",
    muscle: "SHOULDERS",
    categories: ["POWERLIFTING"],
    description:
      "Standing barbell press. Brace hard and press overhead without leaning back.",
  },
  {
    id: "sh2",
    name: "Seated Dumbbell Press",
    muscle: "SHOULDERS",
    categories: [],
    description: "Seated overhead dumbbell press for shoulder mass.",
  },
  {
    id: "sh3",
    name: "Lateral Raise",
    muscle: "SHOULDERS",
    categories: [],
    description: "Dumbbell side raise for medial delt width. Lead with the elbows.",
  },
  {
    id: "sh4",
    name: "Front Raise",
    muscle: "SHOULDERS",
    categories: [],
    description: "Anterior delt isolation; keep range controlled.",
  },
  {
    id: "sh5",
    name: "Rear Delt Fly",
    muscle: "SHOULDERS",
    categories: [],
    description: "Rear delt isolation via reverse pec-deck or dumbbell.",
  },
  {
    id: "sh6",
    name: "Arnold Press",
    muscle: "SHOULDERS",
    categories: [],
    description: "Rotational dumbbell press through full delt sweep.",
  },
  {
    id: "sh7",
    name: "Push Press",
    muscle: "SHOULDERS",
    categories: ["POWERLIFTING", "CROSSFIT"],
    description: "Leg-driven overhead press for bigger loads.",
  },
  {
    id: "sh8",
    name: "Handstand Push-Up",
    muscle: "SHOULDERS",
    categories: ["CALISTHENICS", "CROSSFIT"],
    description: "Bodyweight overhead press against the wall.",
  },

  // LEGS
  {
    id: "lg1",
    name: "Back Squat",
    muscle: "LEGS",
    categories: ["POWERLIFTING"],
    description:
      "High or low bar. Brace, descend under control, drive hips and chest together out of the hole.",
  },
  {
    id: "lg2",
    name: "Front Squat",
    muscle: "LEGS",
    categories: ["OLYMPIC", "POWERLIFTING"],
    description: "Front-rack squat for quad and posture emphasis; stay upright.",
  },
  {
    id: "lg2b",
    name: "Pause Squat",
    muscle: "LEGS",
    categories: ["POWERLIFTING"],
    description: "Pause 2–3 seconds in the hole — builds control and rate of force out of the bottom.",
  },
  {
    id: "lg2c",
    name: "Box Squat",
    muscle: "LEGS",
    categories: ["POWERLIFTING", "STRONGMAN"],
    description: "Sit back to a box, pause, drive — builds posterior-chain strength and control.",
  },
  {
    id: "lg2d",
    name: "Goblet Squat",
    muscle: "LEGS",
    categories: [],
    description: "Dumbbell or kettlebell held at the chest — great squat pattern drill and quad builder.",
  },
  {
    id: "lg2e",
    name: "Hack Squat",
    muscle: "LEGS",
    categories: [],
    description: "Machine or barbell hack squat for quad isolation with the load behind the legs.",
  },
  {
    id: "lg2f",
    name: "Split Squat",
    muscle: "LEGS",
    categories: [],
    description: "Stationary split stance squat — unilateral quad and glute work, knee-friendly.",
  },
  {
    id: "lg2g",
    name: "Step-Up",
    muscle: "LEGS",
    categories: [],
    description: "Drive through one leg onto a box — unilateral leg power and stability.",
  },
  {
    id: "lg2h",
    name: "Good Morning",
    muscle: "LEGS",
    categories: ["POWERLIFTING"],
    description: "Barbell hip-hinge with the weight on the back — posterior chain and lower-back strength.",
  },
  {
    id: "lg2i",
    name: "Reverse Lunge",
    muscle: "LEGS",
    categories: [],
    description: "Step backward into a lunge — less knee stress than forward, glute-biased.",
  },
  {
    id: "lg2j",
    name: "Sumo Squat",
    muscle: "LEGS",
    categories: [],
    description: "Wide-stance squat emphasizing inner thigh and glutes.",
  },
  {
    id: "lg2k",
    name: "Sissy Squat",
    muscle: "LEGS",
    categories: ["CALISTHENICS"],
    description: "Lean-back squat for intense quad isolation; control the depth.",
  },
  {
    id: "lg3",
    name: "Romanian Deadlift",
    muscle: "LEGS",
    categories: [],
    description: "RDL — hip hinge for hamstrings and glutes. Stop short of the floor.",
  },
  {
    id: "lg4",
    name: "Leg Press",
    muscle: "LEGS",
    categories: [],
    description: "Stack-loaded quad press for controlled volume.",
  },
  {
    id: "lg5",
    name: "Walking Lunge",
    muscle: "LEGS",
    categories: [],
    description: "Unilateral leg work; step through under control.",
  },
  {
    id: "lg6",
    name: "Bulgarian Split Squat",
    muscle: "LEGS",
    categories: [],
    description: "Rear-foot-elevated split squat — brutal quad and glute bias.",
  },
  {
    id: "lg7",
    name: "Leg Curl",
    muscle: "LEGS",
    categories: [],
    description: "Hamstring isolation; control the eccentric.",
  },
  {
    id: "lg8",
    name: "Leg Extension",
    muscle: "LEGS",
    categories: [],
    description: "Quad isolation; squeeze at the top.",
  },
  {
    id: "lg9",
    name: "Calf Raise",
    muscle: "LEGS",
    categories: [],
    description: "Standing calf raise; full stretch, pause at the top.",
  },
  {
    id: "lg10",
    name: "Hip Thrust",
    muscle: "LEGS",
    categories: [],
    description: "Glute emphasis; drive through the heels, pause and squeeze.",
  },
  {
    id: "lg11",
    name: "Box Jump",
    muscle: "LEGS",
    categories: ["PLYOMETRIC", "CROSSFIT"],
    description: "Explosive lower-body power. Land soft, step down.",
  },
  {
    id: "lg12",
    name: "Back Extension",
    muscle: "LEGS",
    categories: ["STRETCH"],
    description: "Erector and glute health on the GHD or roman chair.",
  },

  // ARMS
  {
    id: "ar1",
    name: "Barbell Curl",
    muscle: "ARMS",
    categories: [],
    description: "Standing barbell curl for biceps; keep elbows pinned.",
  },
  {
    id: "ar2",
    name: "Dumbbell Curl",
    muscle: "ARMS",
    categories: [],
    description: "Alternating or simultaneous dumbbell curl.",
  },
  {
    id: "ar3",
    name: "Hammer Curl",
    muscle: "ARMS",
    categories: [],
    description: "Neutral-grip curl for brachialis and forearm.",
  },
  {
    id: "ar4",
    name: "Preacher Curl",
    muscle: "ARMS",
    categories: [],
    description: "Isolated biceps on the preacher bench; no swing.",
  },
  {
    id: "ar5",
    name: "Triceps Pushdown",
    muscle: "ARMS",
    categories: [],
    description: "Cable triceps extension; keep elbows tight.",
  },
  {
    id: "ar6",
    name: "Skull Crusher",
    muscle: "ARMS",
    categories: [],
    description: "Lying triceps extension; lower to the forehead.",
  },
  {
    id: "ar7",
    name: "Close-Grip Bench Press",
    muscle: "ARMS",
    categories: ["POWERLIFTING"],
    description: "Triceps-biased bench press; shoulder-width grip.",
  },
  {
    id: "ar8",
    name: "Overhead Triceps Extension",
    muscle: "ARMS",
    categories: [],
    description: "Lengthened triceps work; full overhead stretch.",
  },
  {
    id: "ar9",
    name: "Chin-Up",
    muscle: "ARMS",
    categories: ["CALISTHENICS"],
    description: "Biceps-biased vertical pull with a supinated grip.",
  },
  {
    id: "ar10",
    name: "Wrist Curl",
    muscle: "ARMS",
    categories: [],
    description: "Forearm flexor work; high reps for grip endurance.",
  },

  // CORE
  {
    id: "co1",
    name: "Plank",
    muscle: "CORE",
    categories: ["CALISTHENICS"],
    description: "Anti-extension brace. Stack shoulders over elbows, glutes tight.",
  },
  {
    id: "co2",
    name: "Hanging Leg Raise",
    muscle: "CORE",
    categories: ["CALISTHENICS"],
    description: "Lower-ab flexion; raise legs to parallel or above without swinging.",
  },
  {
    id: "co3",
    name: "Cable Crunch",
    muscle: "CORE",
    categories: [],
    description: "Weighted spinal flexion; curl the chest down, not the hips.",
  },
  {
    id: "co4",
    name: "Ab Wheel Rollout",
    muscle: "CORE",
    categories: ["CALISTHENICS"],
    description: "Anti-extension core strength; don't let the hips sag.",
  },
  {
    id: "co5",
    name: "Russian Twist",
    muscle: "CORE",
    categories: [],
    description: "Rotational core work; controlled, not floppy.",
  },
  {
    id: "co6",
    name: "Side Plank",
    muscle: "CORE",
    categories: ["CALISTHENICS"],
    description: "Lateral core stability; keep hips stacked and lifted.",
  },
  {
    id: "co7",
    name: "Toes to Bar",
    muscle: "CORE",
    categories: ["CROSSFIT", "CALISTHENICS"],
    description: "Strict core flexion; touch toes to the bar, no kip.",
  },
  {
    id: "co8",
    name: "Pallof Press",
    muscle: "CORE",
    categories: [],
    description: "Anti-rotation carryover; press out and resist the pull.",
  },

  // OLYMPIC / STRONGMAN / CROSSFIT / PLYO / STRETCH extras
  {
    id: "ol1",
    name: "Clean & Jerk",
    muscle: "LEGS",
    categories: ["OLYMPIC"],
    description: "Explosive full-body lift — pull, catch, drive overhead.",
  },
  {
    id: "ol2",
    name: "Snatch",
    muscle: "LEGS",
    categories: ["OLYMPIC"],
    description: "Single-rep overhead catch; speed and overhead stability.",
  },
  {
    id: "sm1",
    name: "Farmer's Walk",
    muscle: "BACK",
    categories: ["STRONGMAN"],
    description: "Heavy carry for grip, core, and traps. Stand tall, small steps.",
  },
  {
    id: "sm2",
    name: "Log Press",
    muscle: "SHOULDERS",
    categories: ["STRONGMAN"],
    description: "Overhead press with a log implement; clean from the lap.",
  },
  {
    id: "sm3",
    name: "Atlas Stone Lift",
    muscle: "LEGS",
    categories: ["STRONGMAN"],
    description: "Stone loading for hip power and full-body tension.",
  },
  {
    id: "cf1",
    name: "Burpee",
    muscle: "CHEST",
    categories: ["CROSSFIT", "PLYOMETRIC"],
    description: "Drop, push, jump. Full-body conditioning.",
  },
  {
    id: "cf2",
    name: "Thruster",
    muscle: "LEGS",
    categories: ["CROSSFIT"],
    description: "Front squat straight into an overhead press — one fluid rep.",
  },
  {
    id: "cf3",
    name: "Kettlebell Swing",
    muscle: "LEGS",
    categories: ["CROSSFIT"],
    description: "Hip-driven ballistics; snap the hips, don't squat the bell.",
  },
  {
    id: "pl1",
    name: "Jump Squat",
    muscle: "LEGS",
    categories: ["PLYOMETRIC"],
    description: "Bodyweight explosive squat; land soft and reset.",
  },
  {
    id: "pl2",
    name: "Broad Jump",
    muscle: "LEGS",
    categories: ["PLYOMETRIC"],
    description: "Horizontal power; stick the landing.",
  },
  {
    id: "pl3",
    name: "Clap Push-Up",
    muscle: "CHEST",
    categories: ["PLYOMETRIC", "CALISTHENICS"],
    description: "Explosive chest; push hard enough to clap mid-air.",
  },
  {
    id: "st1",
    name: "Couch Stretch",
    muscle: "LEGS",
    categories: ["STRETCH"],
    description: "Hip flexor mobility; rear foot up against the wall.",
  },
  {
    id: "st2",
    name: "Pigeon Pose",
    muscle: "LEGS",
    categories: ["STRETCH"],
    description: "Hip rotator stretch; square the hips and breathe.",
  },
  {
    id: "st3",
    name: "Hamstring Stretch",
    muscle: "LEGS",
    categories: ["STRETCH"],
    description: "Posterior chain length; hinge at the hip, back flat.",
  },
  {
    id: "st4",
    name: "Thoracic Bridge",
    muscle: "BACK",
    categories: ["STRETCH"],
    description: "T-spine mobility; drive the chest open over the reach.",
  },
  {
    id: "st5",
    name: "Cat-Cow",
    muscle: "CORE",
    categories: ["STRETCH"],
    description: "Spinal mobility flow; segment by segment.",
  },

  // ---- Extra accessories ----
  // CHEST
  {
    id: "ch10",
    name: "Close-Grip Bench Press",
    muscle: "CHEST",
    categories: ["POWERLIFTING"],
    description: "Narrow-grip bench — triceps-biased but still a solid chest builder.",
  },
  {
    id: "ch11",
    name: "Dumbbell Fly",
    muscle: "CHEST",
    categories: [],
    description: "Lying dumbbell fly for a deep pec stretch and isolation.",
  },
  {
    id: "ch12",
    name: "Cable Crossover",
    muscle: "CHEST",
    categories: [],
    description: "High-to-low cable fly for peak contraction across the chest.",
  },
  {
    id: "ch13",
    name: "Pec Deck / Machine Fly",
    muscle: "CHEST",
    categories: [],
    description: "Stack-loaded fly for safe, controlled pec isolation.",
  },
  {
    id: "ch14",
    name: "Deficit Push-Up",
    muscle: "CHEST",
    categories: ["CALISTHENICS", "PLYOMETRIC"],
    description: "Push-up with hands on plates for extra range — chest and triceps.",
  },
  {
    id: "ch15",
    name: "Incline Machine Press",
    muscle: "CHEST",
    categories: [],
    description: "Stack-loaded incline press for upper-chest volume without stabilization cost.",
  },

  // BACK extras
  {
    id: "bk11",
    name: "Chest-Supported Row",
    muscle: "BACK",
    categories: [],
    description: "Row on an incline bench — strict, no body English, great mid-back isolation.",
  },
  {
    id: "bk12",
    name: "T-Bar Row",
    muscle: "BACK",
    categories: [],
    description: "Anchored barbell row for thick, loaded mid-back work.",
  },
  {
    id: "bk13",
    name: "Meadows Row",
    muscle: "BACK",
    categories: [],
    description: "Single-arm landmine row from the floor — lats and upper back with a strong stretch.",
  },
  {
    id: "bk14",
    name: "Single-Arm Lat Pulldown",
    muscle: "BACK",
    categories: [],
    description: "Unilateral cable pulldown for symmetrical lat development.",
  },
  {
    id: "bk15",
    name: "Chin-Up (Weighted)",
    muscle: "BACK",
    categories: ["CALISTHENICS", "POWERLIFTING"],
    description: "Add a dumbbell between the knees or a belt — biceps-biased vertical pull for strength.",
  },
  {
    id: "bk16",
    name: "Straight-Arm Lat Pulldown",
    muscle: "BACK",
    categories: [],
    description: "Cable pullover — isolates the lats without bending the elbows.",
  },

  // SHOULDERS extras
  {
    id: "sh9",
    name: "Landmine Press",
    muscle: "SHOULDERS",
    categories: [],
    description: "Single-arm press of a barbell anchored at one end — shoulder-friendly overhead work.",
  },
  {
    id: "sh10",
    name: "Upright Row",
    muscle: "SHOULDERS",
    categories: [],
    description: "Barbell or cable row to the chin — delts and traps; keep the elbows high.",
  },
  {
    id: "sh11",
    name: "Cable Lateral Raise",
    muscle: "SHOULDERS",
    categories: [],
    description: "Constant-tension side delt isolation via a low cable.",
  },
  {
    id: "sh12",
    name: "Deficit Overhead Press",
    muscle: "SHOULDERS",
    categories: ["POWERLIFTING"],
    description: "Press from blocks or a rack dead-stop — removes leg drive, pure shoulder strength.",
  },
  {
    id: "sh13",
    name: "Z-Press",
    muscle: "SHOULDERS",
    categories: ["CROSSFIT"],
    description: "Seated overhead press with legs straight — strict shoulder and core stability.",
  },

  // ARMS extras
  {
    id: "ar11",
    name: "Incline Dumbbell Curl",
    muscle: "ARMS",
    categories: [],
    description: "Curl on an incline bench for a stretched biceps contraction.",
  },
  {
    id: "ar12",
    name: "Concentration Curl",
    muscle: "ARMS",
    categories: [],
    description: "Braced single-arm curl for a peak biceps contraction.",
  },
  {
    id: "ar13",
    name: "Cable Rope Curl",
    muscle: "ARMS",
    categories: [],
    description: "Rope attachment curl — constant tension, neutral grip option.",
  },
  {
    id: "ar14",
    name: "Triceps Dip",
    muscle: "ARMS",
    categories: ["CALISTHENICS"],
    description: "Upright-torso dip — triceps bias; add weight via belt for strength.",
  },
  {
    id: "ar15",
    name: "Rope Pushdown",
    muscle: "ARMS",
    categories: [],
    description: "Cable rope triceps extension — spread the rope at the bottom for full contraction.",
  },
  {
    id: "ar16",
    name: "Reverse Curl",
    muscle: "ARMS",
    categories: [],
    description: "Overhand-grip curl for brachioradialis and forearm extensors.",
  },
  {
    id: "ar17",
    name: "Farmer's Hold",
    muscle: "ARMS",
    categories: ["STRONGMAN"],
    description: "Stand and hold heavy dumbbells — grip, traps, and core endurance.",
  },

  // CORE extras
  {
    id: "co9",
    name: "Dead Bug",
    muscle: "CORE",
    categories: ["STRETCH"],
    description: "Supine opposite-arm-leg extension — core control and anti-extension.",
  },
  {
    id: "co10",
    name: "Bird Dog",
    muscle: "CORE",
    categories: ["STRETCH"],
    description: "Quadruped opposite-arm-leg reach — anti-rotation and lumbar stability.",
  },
  {
    id: "co11",
    name: "Cable Woodchopper",
    muscle: "CORE",
    categories: [],
    description: "Rotational cable chop — oblique power through a controlled arc.",
  },
  {
    id: "co12",
    name: "Hanging Knee Raise",
    muscle: "CORE",
    categories: ["CALISTHENICS"],
    description: "Bent-knee version of the leg raise — easier entry to hanging core flexion.",
  },
  {
    id: "co13",
    name: "Reverse Crunch",
    muscle: "CORE",
    categories: ["CALISTHENICS"],
    description: "Curl the hips off the floor — lower-ab flexion with no neck strain.",
  },
  {
    id: "co14",
    name: "Hollow Body Hold",
    muscle: "CORE",
    categories: ["CALISTHENICS", "CROSSFIT"],
    description: "Gymnastics-style brace — lower back pressed flat, holds tension.",
  },
  {
    id: "co15",
    name: "Suitcase Carry",
    muscle: "CORE",
    categories: ["STRONGMAN"],
    description: "Single-sided heavy carry — anti-lateral-flexion core strength.",
  },

  // ---- Olympic lifts + accessories ----
  {
    id: "ol3",
    name: "Clean",
    muscle: "LEGS",
    categories: ["OLYMPIC"],
    description:
      "Explosive pull from floor to the shoulders — full-body power. Squat or power catch.",
  },
  {
    id: "ol4",
    name: "Power Clean",
    muscle: "LEGS",
    categories: ["OLYMPIC", "CROSSFIT"],
    description: "Clean caught above a parallel squat — develops explosive hip extension.",
  },
  {
    id: "ol5",
    name: "Power Jerk",
    muscle: "SHOULDERS",
    categories: ["OLYMPIC"],
    description: "Dip and drive the bar overhead with a split or power catch — fast lockout.",
  },
  {
    id: "ol6",
    name: "Split Jerk",
    muscle: "SHOULDERS",
    categories: ["OLYMPIC"],
    description: "Drive the bar overhead and catch in a split stance — maximal overhead fixation.",
  },
  {
    id: "ol7",
    name: "Push Jerk",
    muscle: "SHOULDERS",
    categories: ["OLYMPIC", "CROSSFIT"],
    description: "Dip-drive and drop under the bar into a partial squat — overhead with leg drive.",
  },
  {
    id: "ol8",
    name: "Power Snatch",
    muscle: "LEGS",
    categories: ["OLYMPIC", "CROSSFIT"],
    description: "Snatch caught above a parallel squat — speed and overhead stability.",
  },
  {
    id: "ol9",
    name: "Hang Clean",
    muscle: "LEGS",
    categories: ["OLYMPIC", "CROSSFIT"],
    description: "Clean from the hang (above knee) — isolates the explosive second pull.",
  },
  {
    id: "ol10",
    name: "Hang Snatch",
    muscle: "LEGS",
    categories: ["OLYMPIC", "CROSSFIT"],
    description: "Snatch from the hang — fast, technical, overhead from the hang position.",
  },
  {
    id: "ol11",
    name: "Muscle Clean",
    muscle: "LEGS",
    categories: ["OLYMPIC"],
    description: "Clean with no drop under the bar — pure pull strength to the shoulders.",
  },
  {
    id: "ol12",
    name: "Muscle Snatch",
    muscle: "LEGS",
    categories: ["OLYMPIC"],
    description: "Snatch with no drop under — builds pull power and overhead control.",
  },
  {
    id: "ol13",
    name: "Clean Pull",
    muscle: "LEGS",
    categories: ["OLYMPIC"],
    description: "Clean-grip pull to full extension without catching — overload the pull.",
  },
  {
    id: "ol14",
    name: "Snatch Pull",
    muscle: "LEGS",
    categories: ["OLYMPIC"],
    description: "Snatch-grip pull to full extension — overload the snatch pull.",
  },
  {
    id: "ol15",
    name: "Clean Deadlift",
    muscle: "LEGS",
    categories: ["OLYMPIC"],
    description: "Deadlift with clean technique and setup — positional strength for the clean.",
  },
  {
    id: "ol16",
    name: "Front Squat (Olympic)",
    muscle: "LEGS",
    categories: ["OLYMPIC"],
    description: "Front-rack squat — the catch position strength for the clean.",
  },
  {
    id: "ol17",
    name: "Overhead Squat",
    muscle: "LEGS",
    categories: ["OLYMPIC"],
    description: "Squat with the bar locked overhead — the snatch catch position; demands mobility and stability.",
  },
  {
    id: "ol18",
    name: "Drop Snatch / Snatch Balance",
    muscle: "LEGS",
    categories: ["OLYMPIC"],
    description: "Punch the bar overhead and drop under — builds snatch receiving speed and confidence.",
  },
  {
    id: "ol19",
    name: "Hang Clean Pull",
    muscle: "LEGS",
    categories: ["OLYMPIC"],
    description: "Pull from the hang without catching — explosive hip extension drill.",
  },
  {
    id: "ol20",
    name: "Tall Clean",
    muscle: "LEGS",
    categories: ["OLYMPIC"],
    description: "Clean from a tall standing start — trains the third pull and speed under the bar.",
  },
  {
    id: "ol21",
    name: "Tall Snatch",
    muscle: "LEGS",
    categories: ["OLYMPIC"],
    description: "Snatch from a tall start — pure speed under the bar, no pull momentum.",
  },
  {
    id: "ol22",
    name: "Jerk from Rack",
    muscle: "SHOULDERS",
    categories: ["OLYMPIC"],
    description: "Jerk taken from a rack — heavy overhead work without the clean fatigue.",
  },
  {
    id: "ol23",
    name: "Press Behind Neck",
    muscle: "SHOULDERS",
    categories: ["OLYMPIC"],
    description: "Strict overhead press from behind the neck — overhead and shoulder stability.",
  },

  // ---- Plyometrics ----
  {
    id: "pl4",
    name: "Depth Jump",
    muscle: "LEGS",
    categories: ["PLYOMETRIC"],
    description:
      "Step off a box, land, and immediately jump maximally — builds reactive leg power. High intent.",
  },
  {
    id: "pl5",
    name: "Tuck Jump",
    muscle: "LEGS",
    categories: ["PLYOMETRIC"],
    description: "Jump and drive both knees to the chest — explosive hip flexion and power.",
  },
  {
    id: "pl6",
    name: "Lateral Bound",
    muscle: "LEGS",
    categories: ["PLYOMETRIC"],
    description: "Hop side to side for distance — frontal-plane power and ankle stability.",
  },
  {
    id: "pl7",
    name: "Single-Leg Box Jump",
    muscle: "LEGS",
    categories: ["PLYOMETRIC"],
    description: "Explosive one-legged jump onto a box — unilateral power; land soft.",
  },
  {
    id: "pl8",
    name: "Skater Jump",
    muscle: "LEGS",
    categories: ["PLYOMETRIC", "CROSSFIT"],
    description: "Lateral leap from one leg to the other — quick, reactive conditioning.",
  },
  {
    id: "pl9",
    name: "Pogo Hop",
    muscle: "LEGS",
    categories: ["PLYOMETRIC"],
    description: "Stiff-ankle hops in place — builds lower-leg stiffness and elastic recoil.",
  },
  {
    id: "pl10",
    name: "Box Jump-Down (Depth Drop)",
    muscle: "LEGS",
    categories: ["PLYOMETRIC"],
    description: "Step off a box and stick the landing — absorbs force; eccentric leg control.",
  },
  {
    id: "pl11",
    name: "Medicine Ball Slam",
    muscle: "CORE",
    categories: ["PLYOMETRIC", "CROSSFIT"],
    description: "Explosively slam a ball to the floor — full-body power and core flexion.",
  },
  {
    id: "pl12",
    name: "Wall Ball",
    muscle: "LEGS",
    categories: ["PLYOMETRIC", "CROSSFIT"],
    description: "Squat and throw a ball to a target — conditioning and explosive hip extension.",
  },
  {
    id: "pl13",
    name: "Plyo Push-Up",
    muscle: "CHEST",
    categories: ["PLYOMETRIC", "CALISTHENICS"],
    description: "Explosive push-up so the hands leave the floor — upper-body power.",
  },
  {
    id: "pl14",
    name: "Medicine Ball Chest Pass",
    muscle: "CHEST",
    categories: ["PLYOMETRIC"],
    description: "Explosive chest pass against a wall or partner — upper-body push power.",
  },
  {
    id: "pl15",
    name: "Kettlebell Swing (American)",
    muscle: "LEGS",
    categories: ["PLYOMETRIC", "CROSSFIT"],
    description: "Hip-driven swing to full overhead — ballistic hip extension and conditioning.",
  },
  {
    id: "pl16",
    name: "Squat Jump (Loaded)",
    muscle: "LEGS",
    categories: ["PLYOMETRIC"],
    description: "Barbell or DB-loaded jump squat — power against external resistance.",
  },
  {
    id: "pl17",
    name: "Bounding",
    muscle: "LEGS",
    categories: ["PLYOMETRIC"],
    description: "Exaggerated long running strides — horizontal leg power and stride length.",
  },
  {
    id: "pl18",
    name: "Pike Push-Up Jump",
    muscle: "CHEST",
    categories: ["PLYOMETRIC", "CALISTHENICS"],
    description: "Explosive pike push-up driving the hips high — shoulders and chest power.",
  },

  // ---- Stretches / mobility ----
  {
    id: "st6",
    name: "90/90 Hip Stretch",
    muscle: "LEGS",
    categories: ["STRETCH"],
    description:
      "Sit with legs in a 90/90 front-side split — hip internal and external rotation mobility.",
  },
  {
    id: "st7",
    name: "Frog Stretch",
    muscle: "LEGS",
    categories: ["STRETCH"],
    description: "Wide-knee frog position — deep inner-thigh and hip flexor mobility.",
  },
  {
    id: "st8",
    name: "World's Greatest Stretch",
    muscle: "CORE",
    categories: ["STRETCH"],
    description:
      "Lunge with a rotation and reach — hits hips, thoracic spine, and hamstrings in one move.",
  },
  {
    id: "st9",
    name: "Standing Quad Stretch",
    muscle: "LEGS",
    categories: ["STRETCH"],
    description: "Pull the heel to the glute — quad length; keep the knees stacked.",
  },
  {
    id: "st10",
    name: "Calf Wall Stretch",
    muscle: "LEGS",
    categories: ["STRETCH"],
    description: "Hands on the wall, back heel down — soleus and gastrocnemius length.",
  },
  {
    id: "st11",
    name: "Downward Dog",
    muscle: "LEGS",
    categories: ["STRETCH", "CALISTHENICS"],
    description: "Inverted V — hamstrings, calves, and shoulders; drive the heels down.",
  },
  {
    id: "st12",
    name: "Seated Forward Fold",
    muscle: "LEGS",
    categories: ["STRETCH"],
    description: "Hinge from the hips over straight legs — hamstring and lower-back length.",
  },
  {
    id: "st13",
    name: "Figure-4 Stretch",
    muscle: "LEGS",
    categories: ["STRETCH"],
    description: "Cross one ankle over the opposite knee and recline — glute and piriformis stretch.",
  },
  {
    id: "st14",
    name: "Child's Pose",
    muscle: "CORE",
    categories: ["STRETCH"],
    description: "Kneel and reach the arms long — lats, lower back, and hips; breathe and settle.",
  },
  {
    id: "st15",
    name: "Lat Wall Stretch",
    muscle: "BACK",
    categories: ["STRETCH"],
    description: "Hands on the wall, hips back, chest down — lat and shoulder flexion mobility.",
  },
  {
    id: "st16",
    name: "Chest Doorway Stretch",
    muscle: "CHEST",
    categories: ["STRETCH"],
    description: "Forearm on a doorframe, step through — pec length and shoulder mobility.",
  },
  {
    id: "st17",
    name: "Sleeper Stretch",
    muscle: "SHOULDERS",
    categories: ["STRETCH"],
    description: "Lie on the side and gently push the forearm down — internal rotation for the shoulder.",
  },
  {
    id: "st18",
    name: "Cross-Body Shoulder Stretch",
    muscle: "SHOULDERS",
    categories: ["STRETCH"],
    description: "Pull one arm across the chest — posterior delt and shoulder length.",
  },
  {
    id: "st19",
    name: "Wrist Flexor / Extensor Stretch",
    muscle: "ARMS",
    categories: ["STRETCH"],
    description: "Extend and flex the wrist with gentle assistance — forearm length for healthy elbows.",
  },
  {
    id: "st20",
    name: "Standing Side Bend",
    muscle: "CORE",
    categories: ["STRETCH"],
    description: "Reach overhead and bend sideways — lateral core and lat length.",
  },
  {
    id: "st21",
    name: "Spinal Twist (Supine)",
    muscle: "CORE",
    categories: ["STRETCH"],
    description: "Drop the knees to one side from the back — gentle thoracolumbar rotation.",
  },
  {
    id: "st22",
    name: "Hip Flexor Lunge Stretch",
    muscle: "LEGS",
    categories: ["STRETCH"],
    description: "Kneeling lunge with the hips pressed forward — hip flexor length; squeeze the back glute.",
  },
  {
    id: "st23",
    name: "Adductor Rocking",
    muscle: "LEGS",
    categories: ["STRETCH"],
    description: "Wide-knee kneeling rock back — inner-thigh / adductor mobility.",
  },
  {
    id: "st24",
    name: "Thread-the-Needle",
    muscle: "BACK",
    categories: ["STRETCH"],
    description: "From all fours, thread one arm under the body — thoracic rotation mobility.",
  },
  {
    id: "st25",
    name: "Foam Roll (Thoracic)",
    muscle: "BACK",
    categories: ["STRETCH"],
    description: "Lie back over a roller and extend — t-spine extension and tissue release.",
  },
  {
    id: "st26",
    name: "Foam Roll (Quads)",
    muscle: "LEGS",
    categories: ["STRETCH"],
    description: "Roll the front of the thighs — quad tissue quality and recovery.",
  },
  {
    id: "st27",
    name: "Foam Roll (IT Band / TFL)",
    muscle: "LEGS",
    categories: ["STRETCH"],
    description: "Roll the side of the thigh — lateral leg tissue release.",
  },
  {
    id: "st28",
    name: "Pec / Ball Release",
    muscle: "CHEST",
    categories: ["STRETCH"],
    description: "Pin a lacrosse ball into the pec and move the arm — chest tissue release.",
  },

  // ===== ADDED: extra strength / accessory movements =====
  { id: "ch9", name: "Cable Fly", muscle: "CHEST", categories: ["CALISTHENICS"], description: "Constant-tension chest isolation. Keep a soft elbow and squeeze the pecs at the midline." },
  { id: "ch10", name: "Machine Chest Press", muscle: "CHEST", categories: ["CALISTHENICS"], description: "Beginner-friendly pressing with a fixed path — great for controlled hypertrophy and burnouts." },
  { id: "ch11", name: "Svend Press", muscle: "CHEST", categories: ["CALISTHENICS"], description: "Press two plates together and push straight out — pure inner-chest contraction." },
  { id: "bk9", name: "Chest-Supported Row", muscle: "BACK", categories: ["CALISTHENICS"], description: "Row with your chest on an incline pad to remove momentum and hammer the mid-back." },
  { id: "bk10", name: "Straight-Arm Pulldown", muscle: "BACK", categories: ["CALISTHENICS"], description: "Lat isolation with locked elbows — drive the bar to your thighs feeling the lats stretch and shorten." },
  { id: "bk11", name: "Meadows Row", muscle: "BACK", categories: ["STRONGMAN"], description: "Landmine single-arm row from a staggered stance for a big unilateral lat/upper-back stretch." },
  { id: "sh9", name: "Cable Lateral Raise", muscle: "SHOULDERS", categories: ["CALISTHENICS"], description: "Side-delt isolation with constant cable tension through the full range." },
  { id: "sh10", name: "Face Pull", muscle: "SHOULDERS", categories: ["CALISTHENICS"], description: "Pull a rope to your forehead with high elbows — rear delts and healthy shoulders." },
  { id: "sh11", name: "Z Press", muscle: "SHOULDERS", categories: ["STRONGMAN"], description: "Seated-on-floor overhead press with no back support — brutal core and shoulder stability." },
  { id: "ar9", name: "Incline Dumbbell Curl", muscle: "ARMS", categories: ["CALISTHENICS"], description: "Curl with arms behind the torso for a deep biceps stretch and long-head emphasis." },
  { id: "ar10", name: "Overhead Cable Triceps Extension", muscle: "ARMS", categories: ["CALISTHENICS"], description: "Long-head triceps stretch under load — keep elbows tight and fully extend." },
  { id: "ar11", name: "Hammer Curl", muscle: "ARMS", categories: ["CALISTHENICS"], description: "Neutral-grip curl building the brachialis and forearms for thicker arms." },
  { id: "lg13", name: "Bulgarian Split Squat", muscle: "LEGS", categories: ["CALISTHENICS"], description: "Rear-foot-elevated single-leg squat — quads, glutes and balance with less spinal load." },
  { id: "lg14", name: "Walking Lunge", muscle: "LEGS", categories: ["CALISTHENICS"], description: "Step through long lunges for quad/glute hypertrophy and single-leg stability." },
  { id: "lg15", name: "Seated Leg Curl", muscle: "LEGS", categories: ["CALISTHENICS"], description: "Hamstring isolation — control the eccentric and squeeze hard at full flexion." },
  { id: "lg16", name: "Nordic Ham Curl", muscle: "LEGS", categories: ["CALISTHENICS"], description: "Bodyweight eccentric hamstring builder — lower slowly and resist all the way down." },

  // ===== ADDED: plyometrics =====
  { id: "pl10", name: "Box Jump", muscle: "LEGS", categories: ["PLYOMETRIC"], description: "Explode onto a box, landing soft and stable. Builds triple-extension power. Step down each rep." },
  { id: "pl11", name: "Broad Jump", muscle: "LEGS", categories: ["PLYOMETRIC"], description: "Maximal horizontal jump for distance — arms drive hard and stick the landing." },
  { id: "pl12", name: "Depth Jump", muscle: "LEGS", categories: ["PLYOMETRIC"], description: "Step off a low box, land and immediately rebound up — trains reactive/elastic strength." },
  { id: "pl13", name: "Plyo Push-Up", muscle: "CHEST", categories: ["PLYOMETRIC"], description: "Explosive push-up where the hands leave the floor — upper-body power and rate of force." },
  { id: "pl14", name: "Medicine Ball Slam", muscle: "CORE", categories: ["PLYOMETRIC"], description: "Overhead slam driven by the core and lats — full-body power and conditioning." },
  { id: "pl15", name: "Medicine Ball Rotational Throw", muscle: "CORE", categories: ["PLYOMETRIC"], description: "Throw the ball sideways into a wall — rotational power for athletes and lifters." },
  { id: "pl16", name: "Tuck Jump", muscle: "LEGS", categories: ["PLYOMETRIC"], description: "Jump and pull knees to chest, landing soft — quick reactive lower-body power." },
  { id: "pl17", name: "Lateral Bound", muscle: "LEGS", categories: ["PLYOMETRIC"], description: "Skater-style side-to-side bounds — single-leg power and lateral stability." },

  // ===== ADDED: isometrics (holds) =====
  { id: "iso1", name: "Plank", muscle: "CORE", categories: ["CALISTHENICS"], description: "Isometric hold: brace hard, glutes tight, straight line from head to heels. Add time weekly." },
  { id: "iso2", name: "Side Plank", muscle: "CORE", categories: ["CALISTHENICS"], description: "Isometric anti-lateral-flexion hold on one forearm — obliques and lateral core." },
  { id: "iso3", name: "Wall Sit", muscle: "LEGS", categories: ["CALISTHENICS"], description: "Isometric quad hold at 90 degrees against a wall — burns and builds tendon resilience." },
  { id: "iso4", name: "Hollow Body Hold", muscle: "CORE", categories: ["CALISTHENICS", "CROSSFIT"], description: "Gymnastics isometric: low back pressed to floor, arms and legs off the ground and locked." },
  { id: "iso5", name: "Isometric Mid-Thigh Pull", muscle: "BACK", categories: ["STRONGMAN"], description: "Pull maximally against an immovable bar at mid-thigh — pure force production, low fatigue." },
  { id: "iso6", name: "Bar Hang (Dead Hang)", muscle: "BACK", categories: ["CALISTHENICS"], description: "Isometric grip and shoulder decompression hold — builds grip and healthy shoulders." },
  { id: "iso7", name: "Copenhagen Plank", muscle: "LEGS", categories: ["CALISTHENICS"], description: "Side-plank with top leg on a bench — powerful adductor and groin isometric." },
  { id: "iso8", name: "Spanish Squat Hold", muscle: "LEGS", categories: ["CALISTHENICS"], description: "Band-behind-knees isometric squat hold — knee-friendly quad tension and tendon health." },
];

export type Split = {
  id: string;
  name: string;
  subtitle: string;
  muscles: Muscle[];
  custom?: boolean;
  ai?: boolean;
};

export const splits: Split[] = [
  { id: "push", name: "PUSH", subtitle: "Chest · Shoulders · Triceps", muscles: ["CHEST", "SHOULDERS", "ARMS"] },
  { id: "pull", name: "PULL", subtitle: "Back · Biceps · Rear Delts", muscles: ["BACK", "ARMS", "SHOULDERS"] },
  { id: "legs", name: "LEGS", subtitle: "Quads · Hams · Calves", muscles: ["LEGS"] },
  { id: "upper", name: "UPPER", subtitle: "Chest · Back · Shoulders · Arms", muscles: ["CHEST", "BACK", "SHOULDERS", "ARMS"] },
  { id: "lower", name: "LOWER", subtitle: "Quads · Hams · Glutes · Calves", muscles: ["LEGS"] },
  { id: "arms", name: "ARMS", subtitle: "Biceps · Triceps · Forearms", muscles: ["ARMS"] },
  { id: "core", name: "CORE", subtitle: "Abs · Obliques · Stability", muscles: ["CORE"] },
  { id: "back", name: "BACK", subtitle: "Lats · Traps · Erectors", muscles: ["BACK"] },
  { id: "fullbody", name: "FULL BODY", subtitle: "Total body compound day", muscles: ["CHEST", "BACK", "LEGS", "CORE"] },
  { id: "custom", name: "CUSTOM", subtitle: "Start blank · build your own", muscles: [], custom: true },
];
